import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/providers/nextauthProvider";

import "./globals.css";
import Navbar from "../components/navbar";
import ToastLayout from "@/components/toastLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatbot (using Gemini)",
  description: "Generated by Vercel Ai-SDK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar />
          {children}
          <ToastLayout />
        </NextAuthProvider>
      </body>
    </html>
  );
}
