import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import { ModelProvider } from "@/components/modelSettingContext";
import { ScreenWidthProvider } from "@/hooks/use-screen-width";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScreenWidthProvider>
          <ModelProvider>
            <Navbar />
            {children}
            <Toaster />
          </ModelProvider>
        </ScreenWidthProvider>
      </body>
    </html>
  );
}
